# Generated by Django 5.0.2 on 2024-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0006_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
