# Generated by Django 5.0.2 on 2024-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0007_address_mobile_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default='53.00', max_digits=999999999999),
        ),
    ]
