# Generated by Django 5.0.2 on 2024-03-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0010_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
